Repository exercism/jq, pull requests merged in 2022-11, with the labels that each got.

#67 Run shellcheck and shfmt on the generator script
  bin/generate_tests
  exercises/practice/anagram/test-anagram.bats
  exercises/practice/bob/test-bob.bats
  exercises/practice/collatz-conjecture/test-collatz-conjecture.bats
  exercises/practice/darts/test-darts.bats
  exercises/practice/etl/test-etl.bats
  exercises/practice/hamming/test-hamming.bats
  exercises/practice/hello-world/test-hello-world.bats
  exercises/practice/isogram/test-isogram.bats
  exercises/practice/knapsack/test-knapsack.bats
  exercises/practice/leap/test-leap.bats
  exercises/practice/meetup/test-meetup.bats
  exercises/practice/nth-prime/test-nth-prime.bats
  exercises/practice/nucleotide-count/test-nucleotide-count.bats
  exercises/practice/protein-translation/test-protein-translation.bats
  exercises/practice/proverb/test-proverb.bats
  exercises/practice/raindrops/test-raindrops.bats
  exercises/practice/reverse-string/test-reverse-string.bats
  exercises/practice/rna-transcription/test-rna-transcription.bats
  exercises/practice/satellite/test-satellite.bats
  exercises/practice/scrabble-score/test-scrabble-score.bats
  exercises/practice/sieve/test-sieve.bats
  exercises/practice/space-age/test-space-age.bats
  exercises/practice/transpose/test-transpose.bats
  exercises/practice/two-bucket/test-two-bucket.bats
  exercises/practice/two-fer/test-two-fer.bats
Labels: x:rep/small

#69 Sync recent problem-spec changes
  exercises/practice/atbash-cipher/.meta/config.json
  exercises/practice/beer-song/.meta/config.json
  exercises/practice/bob/.meta/config.json
  exercises/practice/darts/.docs/instructions.md
  exercises/practice/etl/.meta/config.json
  exercises/practice/gigasecond/.meta/config.json
  exercises/practice/hamming/.meta/config.json
  exercises/practice/hello-world/.docs/instructions.md
  exercises/practice/hello-world/.meta/config.json
  exercises/practice/leap/.docs/instructions.md
  exercises/practice/leap/.meta/config.json
  exercises/practice/nth-prime/.meta/config.json
  exercises/practice/nucleotide-count/.meta/config.json
  exercises/practice/protein-translation/.docs/instructions.md
  exercises/practice/proverb/.meta/config.json
  exercises/practice/resistor-color-duo/.docs/instructions.md
  exercises/practice/rna-transcription/.docs/instructions.md
  exercises/practice/rna-transcription/.meta/config.json
  exercises/practice/sieve/.meta/config.json
  exercises/practice/space-age/.docs/instructions.md
  exercises/practice/space-age/.meta/config.json
  exercises/practice/two-bucket/.docs/instructions.md
  exercises/practice/two-bucket/.meta/config.json
Labels: x:rep/tiny

#75 don't use `reverse` in the example solution for reverse-string
  exercises/practice/reverse-string/.meta/example.jq
Labels: x:rep/tiny

#77 Add missing backtick to functions concept docs
  concepts/functions/about.md
  concepts/functions/introduction.md
Labels: x:rep/tiny

#87 Use the forum not gitter for support links
  exercises/shared/.docs/help.md
Labels: x:rep/tiny

#92 basics docs: a missing backtick and inconsistency with header levels
  concepts/basics/about.md
  concepts/basics/introduction.md
  exercises/concept/shopping/.docs/introduction.md
Labels: x:rep/tiny

#93 Numbers concept and Assembly Line exercise
  concepts/numbers/.meta/config.json
  concepts/numbers/about.md
  concepts/numbers/introduction.md
  concepts/numbers/links.json
  concepts/types/about.md
  concepts/types/introduction.md
  concepts/types/links.json
  config.json
  exercises/concept/assembly-line/.docs/hints.md
  exercises/concept/assembly-line/.docs/instructions.md
  exercises/concept/assembly-line/.docs/introduction.md
  exercises/concept/assembly-line/.docs/introduction.md.tpl
  exercises/concept/assembly-line/.meta/config.json
  exercises/concept/assembly-line/.meta/design.md
  exercises/concept/assembly-line/.meta/exemplar.jq
  exercises/concept/assembly-line/assembly-line.jq
  exercises/concept/assembly-line/bats-extra.bash
  exercises/concept/assembly-line/test-assembly-line.bats
Labels: x:rep/large

#96 forgot to re-generate
  exercises/concept/assembly-line/.docs/introduction.md
Labels: x:rep/tiny

#98 assembly line can have speed zero
  exercises/concept/assembly-line/assembly-line.jq
  exercises/concept/assembly-line/test-assembly-line.bats
Labels: x:rep/tiny

#99 slight rewording of numbers as double
  concepts/numbers/about.md
  concepts/numbers/introduction.md
  exercises/concept/assembly-line/.docs/introduction.md
Labels: x:rep/tiny

#101 Assembly Line: fix per-minute function name
  exercises/concept/assembly-line/.meta/exemplar.jq
  exercises/concept/assembly-line/assembly-line.jq
Labels: x:rep/small
