Repository exercism/jq, pull requests merged in 2022-12, with the labels that each got.

#104 Arrays concept
  concepts/arrays/.meta/config.json
  concepts/arrays/about.md
  concepts/arrays/introduction.md
  concepts/arrays/links.json
  config.json
  exercises/concept/bird-count/.docs/hints.md
  exercises/concept/bird-count/.docs/instructions.md
  exercises/concept/bird-count/.docs/introduction.md
  exercises/concept/bird-count/.docs/introduction.md.tpl
  exercises/concept/bird-count/.meta/config.json
  exercises/concept/bird-count/.meta/design.md
  exercises/concept/bird-count/.meta/exemplar.jq
  exercises/concept/bird-count/bats-extra.bash
  exercises/concept/bird-count/bird-count.jq
  exercises/concept/bird-count/bird-counting-data.json
  exercises/concept/bird-count/test-bird-count.bats
Labels: x:rep/large

#108 Objects concept
  concepts/objects/.meta/config.json
  concepts/objects/about.md
  concepts/objects/introduction.md
  concepts/objects/links.json
  config.json
  exercises/concept/high-score-board/.docs/hints.md
  exercises/concept/high-score-board/.docs/instructions.md
  exercises/concept/high-score-board/.docs/introduction.md
  exercises/concept/high-score-board/.docs/introduction.md.tpl
  exercises/concept/high-score-board/.meta/config.json
  exercises/concept/high-score-board/.meta/design.md
  exercises/concept/high-score-board/.meta/exemplar.jq
  exercises/concept/high-score-board/bats-extra.bash
  exercises/concept/high-score-board/high-score-board.jq
  exercises/concept/high-score-board/test-high-score-board.bats
Labels: x:rep/large

#110 Expand on the `del` function
  concepts/objects/about.md
  concepts/objects/introduction.md
  exercises/concept/high-score-board/.docs/hints.md
  exercises/concept/high-score-board/.docs/introduction.md
Labels: x:rep/small

#111 add pull request template
  .github/pull_request_template.md
Labels: x:rep/tiny

#114 Conditionals concept
  concepts/comparison/.meta/config.json
  concepts/comparison/about.md
  concepts/comparison/introduction.md
  concepts/comparison/links.json
  concepts/conditionals/.meta/config.json
  concepts/conditionals/about.md
  concepts/conditionals/introduction.md
  concepts/conditionals/links.json
  config.json
  exercises/concept/vehicle-purchase/.docs/hints.md
  exercises/concept/vehicle-purchase/.docs/instructions.md
  exercises/concept/vehicle-purchase/.docs/introduction.md
  exercises/concept/vehicle-purchase/.docs/introduction.md.tpl
  exercises/concept/vehicle-purchase/.meta/config.json
  exercises/concept/vehicle-purchase/.meta/design.md
  exercises/concept/vehicle-purchase/.meta/exemplar.jq
  exercises/concept/vehicle-purchase/bats-extra.bash
  exercises/concept/vehicle-purchase/test-vehicle-purchase.bats
  exercises/concept/vehicle-purchase/vehicle-purchase.jq
Labels: x:rep/large

#117 Add missing spaces
  concepts/objects/about.md
  concepts/objects/introduction.md
  exercises/concept/high-score-board/.docs/introduction.md
Labels: x:rep/small

#118 Recursion concept
  concepts/recursion/.meta/config.json
  concepts/recursion/about.md
  concepts/recursion/introduction.md
  concepts/recursion/links.json
  config.json
  exercises/concept/recursive-functions/.docs/hints.md
  exercises/concept/recursive-functions/.docs/instructions.md
  exercises/concept/recursive-functions/.docs/introduction.md
  exercises/concept/recursive-functions/.docs/introduction.md.tpl
  exercises/concept/recursive-functions/.meta/config.json
  exercises/concept/recursive-functions/.meta/design.md
  exercises/concept/recursive-functions/.meta/exemplar.jq
  exercises/concept/recursive-functions/bats-extra.bash
  exercises/concept/recursive-functions/recursive-functions.jq
  exercises/concept/recursive-functions/test-recursive-functions.bats
Labels: x:rep/large
