Repository exercism/jq, pull requests merged in 2023-09, with the labels that each got.

#181 Sync track docs and configs
  exercises/practice/darts/.docs/instructions.md
  exercises/practice/resistor-color-trio/.docs/instructions.md
Labels: x:size/small, x:rep/small, x:action/sync

#182 Fix typo in instructions
  exercises/concept/vehicle-purchase/.docs/hints.md
  exercises/concept/vehicle-purchase/.docs/instructions.md
  exercises/concept/vehicle-purchase/.meta/exemplar.jq
  exercises/concept/vehicle-purchase/vehicle-purchase.jq
Labels: x:size/small, x:action/fix, x:rep/small

#184 Fix links to jq manual
  exercises/practice/two-fer/two-fer.jq
Labels: x:size/tiny, x:action/fix, x:type/docs, x:rep/tiny

#185 Fix a typo in instructions.md
  exercises/concept/recursive-functions/.docs/instructions.md
Labels: x:size/tiny, x:action/fix, x:type/docs, x:rep/tiny

#186 Convert backtick (`) admonition fences to tildes (~)
  exercises/practice/etl/.docs/instructions.md
  exercises/practice/gigasecond/.docs/introduction.md
  exercises/practice/rna-transcription/.docs/instructions.md
  exercises/practice/rna-transcription/.docs/introduction.md
  exercises/practice/sieve/.docs/instructions.md
Labels: x:size/tiny

#187 fix two typos
  exercises/concept/assembly-line/assembly-line.jq
  exercises/concept/shopping/.docs/hints.md
Labels: x:size/tiny, x:type/docs, x:rep/tiny

#188 Add task numbers to headings in concept exercises
  exercises/concept/grade-stats/.docs/hints.md
  exercises/concept/grade-stats/.docs/instructions.md
  exercises/concept/regular-chatbot/.docs/instructions.md
Labels: x:size/small, x:action/fix, x:rep/small
