Repository exercism/jq, pull requests merged in 2023-01, with the labels that each got.

#119 Apply consistent formatting to concepts docs
  concepts/arrays/about.md
  concepts/arrays/introduction.md
  concepts/basics/about.md
  concepts/basics/introduction.md
  concepts/comparison/about.md
  concepts/comparison/introduction.md
  concepts/conditionals/about.md
  concepts/conditionals/introduction.md
  concepts/functions/about.md
  concepts/functions/introduction.md
  concepts/numbers/about.md
  concepts/numbers/introduction.md
  concepts/objects/about.md
  concepts/objects/introduction.md
  concepts/recursion/about.md
  concepts/recursion/introduction.md
  concepts/strings/about.md
  concepts/strings/introduction.md
  concepts/variables/about.md
  concepts/variables/introduction.md
  exercises/concept/assembly-line/.docs/introduction.md
  exercises/concept/bird-count/.docs/introduction.md
  exercises/concept/high-score-board/.docs/introduction.md
  exercises/concept/lasagna/.docs/introduction.md
  exercises/concept/log-line-parser/.docs/introduction.md
  exercises/concept/recursive-functions/.docs/introduction.md
  exercises/concept/remote-control-car/.docs/introduction.md
  exercises/concept/shopping/.docs/introduction.md
  exercises/concept/vehicle-purchase/.docs/introduction.md
Labels: x:size/medium, x:module/concept, x:type/content, x:type/docs

#121 Sync recent problem-spec changes
  exercises/practice/meetup/.docs/instructions.md
  exercises/practice/resistor-color-trio/.docs/instructions.md
  exercises/practice/resistor-color-trio/.meta/example.jq
  exercises/practice/resistor-color-trio/.meta/tests.toml
  exercises/practice/resistor-color-trio/test-resistor-color-trio.bats
  exercises/practice/space-age/.docs/instructions.md
Labels: x:rep/small

#123 split README. forego grep exercise
  CONTRIBUTING.md
  README.md
  config.json
Labels: x:rep/tiny

#124 Ensure links to the jq manual use the v1.6 version
  concepts/functions/about.md
  concepts/functions/introduction.md
  concepts/functions/links.json
  docs/ABOUT.md
  exercises/practice/two-fer/two-fer.jq
Labels: x:rep/tiny

#125 Regex concept
  concepts/recursion/.meta/config.json
  concepts/regular-expressions/.meta/config.json
  concepts/regular-expressions/about.md
  concepts/regular-expressions/introduction.md
  concepts/regular-expressions/links.json
  config.json
  exercises/concept/regular-chatbot/.docs/hints.md
  exercises/concept/regular-chatbot/.docs/instructions.md
  exercises/concept/regular-chatbot/.docs/introduction.md
  exercises/concept/regular-chatbot/.docs/introduction.md.tpl
  exercises/concept/regular-chatbot/.meta/config.json
  exercises/concept/regular-chatbot/.meta/design.md
  exercises/concept/regular-chatbot/.meta/exemplar.jq
  exercises/concept/regular-chatbot/bats-extra.bash
  exercises/concept/regular-chatbot/regular-chatbot.jq
  exercises/concept/regular-chatbot/test-regular-chatbot.bats
  exercises/concept/remote-control-car/.docs/introduction.md
  exercises/concept/shopping/.docs/introduction.md
Labels: x:rep/large

#128 putting quotes in a bats test name is bad
  exercises/concept/regular-chatbot/test-regular-chatbot.bats
Labels: x:rep/small

#129 Reduce concept
  concepts/reduce/.meta/config.json
  concepts/reduce/about.md
  concepts/reduce/introduction.md
  concepts/reduce/links.json
  config.json
  exercises/concept/grade-stats/.docs/hints.md
  exercises/concept/grade-stats/.docs/instructions.md
  exercises/concept/grade-stats/.docs/introduction.md
  exercises/concept/grade-stats/.docs/introduction.md.tpl
  exercises/concept/grade-stats/.meta/config.json
  exercises/concept/grade-stats/.meta/design.md
  exercises/concept/grade-stats/.meta/exemplar.jq
  exercises/concept/grade-stats/bats-extra.bash
  exercises/concept/grade-stats/grade-stats.jq
  exercises/concept/grade-stats/grades.json
  exercises/concept/grade-stats/test-grade-stats.bats
Labels: x:rep/large

#130 broken link in admonition
  concepts/reduce/introduction.md
Labels: x:rep/tiny

#133 Rework syllabus
  concepts/compare/.meta/config.json
  concepts/compare/about.md
  concepts/compare/introduction.md
  concepts/compare/links.json
  config.json
  exercises/concept/vehicle-purchase/.docs/introduction.md
  exercises/concept/vehicle-purchase/.docs/introduction.md.tpl
  exercises/concept/vehicle-purchase/.meta/design.md
Labels: x:rep/small

#134 what happens if we swap numbers & strings?
  config.json
Labels: x:rep/tiny

#136 prettier
  .prettierignore
  CONTRIBUTING.md
  concepts/arrays/about.md
  concepts/arrays/introduction.md
  concepts/basics/about.md
  concepts/basics/introduction.md
  concepts/compare/about.md
  concepts/compare/introduction.md
  concepts/conditionals/about.md
  concepts/conditionals/introduction.md
  concepts/functions/about.md
  concepts/functions/introduction.md
  concepts/objects/about.md
  concepts/objects/introduction.md
  concepts/recursion/.meta/config.json
  concepts/recursion/about.md
  concepts/reduce/.meta/config.json
  concepts/reduce/about.md
  concepts/reduce/introduction.md
  concepts/regular-expressions/.meta/config.json
  concepts/regular-expressions/about.md
  concepts/regular-expressions/introduction.md
  concepts/strings/about.md
  concepts/strings/introduction.md
  concepts/variables/introduction.md
  exercises/concept/assembly-line/.docs/instructions.md
  exercises/concept/assembly-line/.meta/design.md
  exercises/concept/bird-count/.docs/introduction.md
  exercises/concept/grade-stats/.docs/instructions.md
  exercises/concept/grade-stats/.docs/introduction.md
  exercises/concept/high-score-board/.docs/hints.md
  exercises/concept/high-score-board/.docs/instructions.md
  exercises/concept/high-score-board/.docs/introduction.md
  exercises/concept/high-score-board/.meta/design.md
  exercises/concept/lasagna/.docs/introduction.md
  exercises/concept/log-line-parser/.docs/introduction.md
  exercises/concept/log-line-parser/.meta/design.md
  exercises/concept/regular-chatbot/.docs/hints.md
  exercises/concept/regular-chatbot/.docs/instructions.md
  exercises/concept/regular-chatbot/.docs/introduction.md
  exercises/concept/remote-control-car/.docs/introduction.md
  exercises/concept/shopping/.docs/introduction.md
  exercises/concept/vehicle-purchase/.docs/hints.md
  exercises/concept/vehicle-purchase/.docs/introduction.md
  exercises/concept/vehicle-purchase/.meta/design.md
Labels: x:rep/small

#138 Go Live
  config.json
Labels: x:rep/tiny

#141 Fix typo in Variables concept
  concepts/variables/about.md
  concepts/variables/introduction.md
  exercises/concept/lasagna/.docs/introduction.md
Labels: x:size/small, x:action/fix, x:module/concept, x:type/docs

#142 Add note on output
  concepts/basics/about.md
  concepts/basics/introduction.md
  exercises/concept/shopping/.docs/introduction.md
Labels: x:size/tiny, x:type/content, x:type/docs
