Repository exercism/jq, pull requests merged in 2023-03, with the labels that each got.

#150 Append jq-specific instructions to gigasecond
  exercises/practice/gigasecond/.docs/instructions.append.md
Labels: x:rep/small

#152 Fix typo in arrays doc
  concepts/arrays/about.md
Labels: x:size/tiny, x:action/fix, x:type/docs

#156 configlet sync --docs
  exercises/practice/bob/.docs/instructions.md
  exercises/practice/bob/.docs/introduction.md
  exercises/practice/gigasecond/.docs/introduction.md
  exercises/practice/sieve/.docs/instructions.md
  exercises/practice/sieve/.docs/introduction.md
  exercises/practice/two-fer/.docs/instructions.md
Labels: x:rep/tiny

#159 ISSUE-157: about.md file missing fix
  concepts/basics/about.md
Labels: x:rep/tiny
