Repository exercism/jq, pull requests merged in 2024-01, with the labels that each got.

#201 sync track
  exercises/practice/hello-world/.meta/config.json
  exercises/practice/knapsack/.meta/tests.toml
  exercises/practice/pop-count/.meta/config.json
  exercises/practice/transpose/.meta/config.json
Labels: x:rep/tiny

#205 Sync leap
  exercises/practice/leap/.docs/instructions.md
  exercises/practice/leap/.docs/introduction.md
  exercises/practice/leap/.meta/config.json
Labels: x:rep/tiny

#207 leap: sync
  exercises/practice/leap/.docs/introduction.md
Labels: x:size/tiny

#212 tweaks to regex concept docs
  concepts/regular-expressions/about.md
  concepts/regular-expressions/introduction.md
  docs/INSTALLATION.md
  exercises/concept/regular-chatbot/.docs/introduction.md
Labels: x:rep/small

#214 Sync fetch-configlet.ps1 script
  bin/fetch-configlet.ps1
Labels: x:size/tiny
