Repository exercism/jq, pull requests merged in 2024-07, with the labels that each got.

#243 Sync new protein translation test case; sync docs and metadata
  exercises/practice/pig-latin/.docs/instructions.md
  exercises/practice/protein-translation/.meta/tests.toml
  exercises/practice/protein-translation/test-protein-translation.bats
  exercises/practice/resistor-color-duo/.docs/instructions.md
  exercises/practice/yacht/.meta/config.json
Labels: x:module/practice-exercise, x:action/sync

#250 resistor-color-trio: sync
  exercises/practice/resistor-color-trio/.docs/instructions.md
Labels: x:size/tiny

#249 resistor-color-duo: sync
  exercises/practice/resistor-color-duo/.docs/instructions.md
Labels: x:size/tiny

#248 resistor-color: sync
  exercises/practice/resistor-color/.docs/instructions.md
Labels: x:size/tiny

#253 Fix typos in minesweeper append doc
  exercises/practice/minesweeper/.docs/instructions.append.md
Labels: x:rep/tiny

#259 "Pascal's" triangle
  config.json
Labels: x:rep/tiny
